import "./bootstrap";
import "./jquery";
import "flowbite";
import "./loginAdmin";
import "./customSelect";
import "./script";
import "./categorie";
import "./brand";
import "./product";
import "./modal-image";
import "./flash-offers";
import "./popup";
import "./user";
import "./faq";
import "./swiper";
import "./product-view";
import "./cart";
import "./drawer";
import "./sales-strategies";
import { initSwiper } from "./swiper";

initSwiper();
